// Central Hugeicons registry. All site icons resolve from here so swaps live
// in one place. Icons are SVG data objects passed to <Icon icon={...} />.
import {
  // nav / ui
  Menu01Icon,
  Cancel01Icon,
  ArrowRight01Icon,
  ArrowDown01Icon,
  Tick02Icon,
  CheckmarkCircle02Icon,
  PlusSignIcon,
  SparklesIcon,
  SentIcon,
  Search01Icon,
  Notification01Icon,
  StarIcon,
  QuoteUpIcon,
  // contact
  Mail01Icon,
  SmartPhone01Icon,
  Location01Icon,
  // banking / features
  UserMultipleIcon,
  PiggyBankIcon,
  BankIcon,
  ArrowDataTransferHorizontalIcon,
  Wallet01Icon,
  PercentCircleIcon,
  BookOpen01Icon,
  SecurityCheckIcon,
  Building03Icon,
  Analytics01Icon,
  Globe02Icon,
  Layers01Icon,
  // how it works / value
  Configuration01Icon,
  Rocket01Icon,
  ChartUpIcon,
  ViewIcon,
  FlashIcon,
  // product preview
  DashboardSquare01Icon,
  Calendar01Icon,
  Alert01Icon,
  UserCircleIcon,
  Settings01Icon,
  CreditCardIcon,
  Invoice01Icon,
  ChartIncreaseIcon,
  // clients
  Coins01Icon,
  Diamond01Icon,
  Briefcase01Icon,
  BalanceScaleIcon,
  Money01Icon,
  DollarCircleIcon,
  // problem section
  File02Icon,
  Clock01Icon,
  JusticeScaleIcon,
  UserRemove01Icon,
  ComputerRemoveIcon,
  GitBranchIcon,
  PieChart01Icon,
} from '@hugeicons/core-free-icons'

export {
  Menu01Icon,
  Cancel01Icon,
  ArrowRight01Icon,
  ArrowDown01Icon,
  Tick02Icon,
  CheckmarkCircle02Icon,
  PlusSignIcon,
  SparklesIcon,
  SentIcon,
  Search01Icon,
  Notification01Icon,
  StarIcon,
  QuoteUpIcon,
  Mail01Icon,
  SmartPhone01Icon,
  Location01Icon,
  UserMultipleIcon,
  PiggyBankIcon,
  BankIcon,
  ArrowDataTransferHorizontalIcon,
  Wallet01Icon,
  PercentCircleIcon,
  BookOpen01Icon,
  SecurityCheckIcon,
  Building03Icon,
  Analytics01Icon,
  Globe02Icon,
  Layers01Icon,
  Configuration01Icon,
  Rocket01Icon,
  ChartUpIcon,
  ViewIcon,
  FlashIcon,
  DashboardSquare01Icon,
  Calendar01Icon,
  Alert01Icon,
  UserCircleIcon,
  Settings01Icon,
  CreditCardIcon,
  Invoice01Icon,
  ChartIncreaseIcon,
  Coins01Icon,
  Diamond01Icon,
  Briefcase01Icon,
  BalanceScaleIcon,
  Money01Icon,
  DollarCircleIcon,
  File02Icon,
  Clock01Icon,
  JusticeScaleIcon,
  UserRemove01Icon,
  ComputerRemoveIcon,
  GitBranchIcon,
  PieChart01Icon,
}
